### ISSUE TITLE
Object #<Object> has no method 'silent'

### ISSUE THREAD

**Issue by drnic** [arturadib/botio#13]
Any suggestions on why I get this error?

```
$ node -v
v0.10.30
$ npm -v 
1.4.21
$ botio bootstrap --repo drnic/botio-test-app.js

/usr/local/lib/node_modules/botio/lib/bootstrap.js:9
shell.silent();
      ^
TypeError: Object #<Object> has no method 'silent'
    at Object.<anonymous> (/usr/local/lib/node_modules/botio/lib/bootstrap.js:9:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Command.program.command.description.option.option.action.global.user (/usr/local/lib/node_modules/botio/bin/botio:20:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/botio/node_modules/commander/lib/commander.js:232:8)
    at Command.emit (events.js:98:17)
```

**Comment by WaveringAna** [comment]
having the same issue as well

```
$ botio bootstrap --repo z-classic/z-nomp
/usr/local/lib/node_modules/botio/lib/bootstrap.js:9
shell.silent();
      ^

TypeError: shell.silent is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/botio/lib/bootstrap.js:9:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Command.<anonymous> (/usr/local/lib/node_modules/botio/bin/botio:20:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/botio/node_modules/commander/lib/commander.js:232:8)
aayan@AayansDesktopLinux:~/git/botio$ node -v
v7.9.0
aayan@AayansDesktopLinux:~/git/botio$ npm -v
4.2.0
```

**Comment by WaveringAna** [comment]
It works with shelljs `0.0.5pre4`
